module.exports =
  qsf_value: "全水(%)"
  hf_value: "灰分(%)"
  hff_value: "挥发份(%)"
  qlf_value: "硫分(%)"
  rezhi_value: "热值(Kcal)"
  hrd_value: "灰熔点(℃)"
  njzs_value: "G值"
  jzchd_value: "Y值"
  # ganguo_value: "坩埚/自由膨胀序数(CSN/FSI)"
  # hskmzs_value: "哈氏可磨(HGI)"
  # lidu_value_min: "粒度(MM)"
  # gdt_value: "固定碳(FC)"
  # jztz_value: "焦渣特性(CRC)"
  # ksqd_value: "抗碎强度(M40/M25)"
  # nmqd_value: "耐磨强度(M10)"
  # fyhqd_value: "反应后强度(CSR)"
  # jtfyy_value: "焦炭反应性"
